### ISSUE TITLE
practica 1 analisis de aplicacion de realidad aumentada 

### ISSUE THREAD

**Issue by AlejandroReyes99** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-AlejandroReyes99#2]
[practica1_RealidadAumentada.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-AlejandroReyes99/files/6125306/practica1_RealidadAumentada.pdf)

**Comment by ArteezyOne** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
